#!/bin/bash
#https://courses.missouristate.edu/kenvollmar/mars/Help/Help_4_1/MarsHelpCommand.html


# petite bidouille pour pouvoir appeler depuis n'importe où
# en ne mettant en argument que main.s (et pas mips_libs/main.s)
curr_path=$(dirname $0)
a=()
for d in "$@"; do
    a+=( "$curr_path/$d" )
done


java -jar $curr_path/Mars4_5.jar ${a[@]}

